# syntax=docker/dockerfile:1
##################################################
# Nginx with HTTP/3, Brotli, Headers More
##################################################
FROM alpine:latest AS builder
